package org.example.model;

public enum MessageType {
    ADD_USER, TEXT_MESSAGE, USER_LOGIN_FAIL, USER_LOGIN_SUCCESSFUL, USER_LOGOUT, USER_LOGOUT_FAIL, USER_LOGOUT_SUCCESSFUL, SERVER_JOINED, SERVER_EXITED

}